### ISSUE TITLE
Animated Image is getting blocked by CORS

### ISSUE THREAD

**Issue by unnikrishnan-r** [unnikrishnan-r/Giphy-API#1]
https://drive.google.com/file/d/1_tpDbF5_E5r_fANqyl4ujz54lPOvfNfJ/view

The animated url from Giphy API is getting blocked.

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://giphy.com/gifs/tiger-cat-black-and-white-Cr7AfrUbRatmo with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

API Call: http://api.giphy.com/v1/gifs/search?q=TIGER&apikey=vT2XZqQdvN88TSL4h9wqV8pXsXJWj10d&limit=3

**Animated URL**

`"url": "https://giphy.com/gifs/tiger-cat-black-and-white-Cr7AfrUbRatmo" 
`
**Static URL**
```
"original_still": {
"url": "https://media0.giphy.com/media/Cr7AfrUbRatmo/giphy_s.gif?cid=e3b0c4425d2a8021576f2f4c633a693f&rid=giphy_s.gif"
```

**Comment by unnikrishnan-r** [comment]
Fixed by using the below element in API response:

```downsized: object 
Data on a version of this GIF downsized to be under 2mb.    url: string 
The publicly-accessible direct URL for this GIF.    "https://media1.giphy.com/media/cZ7rmKfFYOvYI/giphy-downsized.gif"```

**Comment by changyeamoon** [comment]
> Fixed by using the below element in API response:
> 
> ```
> Data on a version of this GIF downsized to be under 2mb.    url: string 
> The publicly-accessible direct URL for this GIF.    "https://media1.giphy.com/media/cZ7rmKfFYOvYI/giphy-downsized.gif"```
> ```

Can you explain how this fixed it? 👀

**Comment by unnikrishnan-r** [comment]
> > Fixed by using the below element in API response:
> > ```
> > Data on a version of this GIF downsized to be under 2mb.    url: string 
> > The publicly-accessible direct URL for this GIF.    "https://media1.giphy.com/media/cZ7rmKfFYOvYI/giphy-downsized.gif"```
> > ```
> 
> Can you explain how this fixed it? 👀

@changyeamoon Sorry man, Honestly I don't remember. Was almost 2 years ago.
I am assuming the original call was blocked for some reason
